import { CaptionStyleConfig, CaptionStyleType, VideoType, WordAnimationEffect } from '../types';

const defaultBase = {
  scaleX: 100,
  scaleY: 100,
  rotation: 0,
  letterSpacing: 0,
  lineHeight: 1.3,
  hasShadow: false,
  shadowBlur: 0,
  shadowColor: 'rgba(0, 0, 0, 0.6)',
};

export const DEFAULT_STYLE_PRESETS: Record<CaptionStyleType, Record<VideoType, CaptionStyleConfig>> = {
  viral: {
    short: {
      ...defaultBase,
      styleType: 'viral',
      fontFamily: 'Cairo',
      fontSize: 48, // Big, bold, easily readable on mobile
      primaryColor: '#FFFFFF',
      highlightColor: '#FACC15', // Vibrant Yellow
      strokeColor: '#000000',
      strokeWidth: 4,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 74, // Safe center-bottom above UI
      wordsPerLine: 4,
      animation: 'pop',
      wordEffect: 'karaoke_highlight',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'viral',
      fontFamily: 'Cairo',
      fontSize: 30, // Clear and crisp for 16:9 landscape
      primaryColor: '#FFFFFF',
      highlightColor: '#FACC15',
      strokeColor: '#000000',
      strokeWidth: 2.5,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 86, // Bottom Center safe area
      wordsPerLine: 8,
      animation: 'pop',
      wordEffect: 'karaoke_highlight',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  colorful: {
    short: {
      ...defaultBase,
      styleType: 'colorful',
      fontFamily: 'Tajawal',
      fontSize: 48,
      primaryColor: '#FFFFFF',
      highlightColor: '#38BDF8',
      strokeColor: '#020617',
      strokeWidth: 4,
      backgroundColor: 'rgba(15, 23, 42, 0.7)',
      backgroundOpacity: 70,
      positionXPercent: 50,
      positionYPercent: 74,
      wordsPerLine: 4,
      animation: 'glow',
      wordEffect: 'color_wave',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'colorful',
      fontFamily: 'Tajawal',
      fontSize: 30,
      primaryColor: '#FFFFFF',
      highlightColor: '#38BDF8',
      strokeColor: '#020617',
      strokeWidth: 2.5,
      backgroundColor: 'rgba(15, 23, 42, 0.75)',
      backgroundOpacity: 75,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 8,
      animation: 'glow',
      wordEffect: 'color_wave',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  clean: {
    short: {
      ...defaultBase,
      styleType: 'clean',
      fontFamily: 'Almarai',
      fontSize: 46,
      primaryColor: '#FFFFFF',
      highlightColor: '#38BDF8',
      strokeColor: '#000000',
      strokeWidth: 3.5,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      backgroundOpacity: 70,
      positionXPercent: 50,
      positionYPercent: 74,
      wordsPerLine: 4,
      animation: 'fade',
      wordEffect: 'classic',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'clean',
      fontFamily: 'Almarai',
      fontSize: 28,
      primaryColor: '#FFFFFF',
      highlightColor: '#38BDF8',
      strokeColor: '#000000',
      strokeWidth: 2.5,
      backgroundColor: 'rgba(0, 0, 0, 0.75)',
      backgroundOpacity: 75,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 8,
      animation: 'fade',
      wordEffect: 'classic',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  highlight: {
    short: {
      ...defaultBase,
      styleType: 'highlight',
      fontFamily: 'Readex Pro',
      fontSize: 48,
      primaryColor: '#E2E8F0',
      highlightColor: '#10B981',
      strokeColor: '#000000',
      strokeWidth: 4,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 74,
      wordsPerLine: 4,
      animation: 'bounce',
      wordEffect: 'pop_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'highlight',
      fontFamily: 'Readex Pro',
      fontSize: 30,
      primaryColor: '#E2E8F0',
      highlightColor: '#10B981',
      strokeColor: '#000000',
      strokeWidth: 2.5,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 8,
      animation: 'bounce',
      wordEffect: 'pop_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  quran_gold: {
    short: {
      ...defaultBase,
      styleType: 'quran_gold',
      fontFamily: 'Amiri',
      fontSize: 52,
      primaryColor: '#FFFBEB',
      highlightColor: '#F59E0B',
      strokeColor: '#042F2E',
      strokeWidth: 3.5,
      backgroundColor: 'rgba(4, 47, 46, 0.85)',
      backgroundOpacity: 85,
      positionXPercent: 50,
      positionYPercent: 74,
      wordsPerLine: 4,
      animation: 'fade',
      wordEffect: 'karaoke_highlight',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'quran_gold',
      fontFamily: 'Amiri',
      fontSize: 34,
      primaryColor: '#FFFBEB',
      highlightColor: '#F59E0B',
      strokeColor: '#042F2E',
      strokeWidth: 2.5,
      backgroundColor: 'rgba(4, 47, 46, 0.85)',
      backgroundOpacity: 85,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 7,
      animation: 'fade',
      wordEffect: 'karaoke_highlight',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  neon_cyber: {
    short: {
      ...defaultBase,
      styleType: 'neon_cyber',
      fontFamily: 'Alexandria',
      fontSize: 48,
      primaryColor: '#FFFFFF',
      highlightColor: '#38BDF8',
      strokeColor: '#020617',
      strokeWidth: 4.5,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 74,
      wordsPerLine: 4,
      animation: 'glow',
      wordEffect: 'glow_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'neon_cyber',
      fontFamily: 'Alexandria',
      fontSize: 30,
      primaryColor: '#FFFFFF',
      highlightColor: '#38BDF8',
      strokeColor: '#020617',
      strokeWidth: 2.5,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 7,
      animation: 'glow',
      wordEffect: 'glow_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  podcast_box: {
    short: {
      ...defaultBase,
      styleType: 'podcast_box',
      fontFamily: 'Readex Pro',
      fontSize: 44,
      primaryColor: '#FFFFFF',
      highlightColor: '#38BDF8',
      strokeColor: '#000000',
      strokeWidth: 2,
      backgroundColor: 'rgba(15, 23, 42, 0.9)',
      backgroundOpacity: 90,
      positionXPercent: 50,
      positionYPercent: 76,
      wordsPerLine: 4,
      animation: 'pop',
      wordEffect: 'box_active',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'podcast_box',
      fontFamily: 'Readex Pro',
      fontSize: 28,
      primaryColor: '#FFFFFF',
      highlightColor: '#38BDF8',
      strokeColor: '#000000',
      strokeWidth: 1.5,
      backgroundColor: 'rgba(15, 23, 42, 0.9)',
      backgroundOpacity: 90,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 8,
      animation: 'pop',
      wordEffect: 'box_active',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  mrbeast: {
    short: {
      ...defaultBase,
      styleType: 'mrbeast',
      fontFamily: 'Changa',
      fontSize: 52,
      primaryColor: '#FFFFFF',
      highlightColor: '#EF4444',
      strokeColor: '#000000',
      strokeWidth: 5,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 72,
      wordsPerLine: 3,
      animation: 'bounce',
      wordEffect: 'pop_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'mrbeast',
      fontFamily: 'Changa',
      fontSize: 32,
      primaryColor: '#FFFFFF',
      highlightColor: '#EF4444',
      strokeColor: '#000000',
      strokeWidth: 3,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 6,
      animation: 'bounce',
      wordEffect: 'pop_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  islamic_emerald: {
    short: {
      ...defaultBase,
      styleType: 'islamic_emerald',
      fontFamily: 'Tajawal',
      fontSize: 48,
      primaryColor: '#FFFFFF',
      highlightColor: '#34D399',
      strokeColor: '#064E3B',
      strokeWidth: 3.5,
      backgroundColor: 'rgba(6, 78, 59, 0.88)',
      backgroundOpacity: 88,
      positionXPercent: 50,
      positionYPercent: 75,
      wordsPerLine: 4,
      animation: 'fade',
      wordEffect: 'karaoke_highlight',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'islamic_emerald',
      fontFamily: 'Tajawal',
      fontSize: 30,
      primaryColor: '#FFFFFF',
      highlightColor: '#34D399',
      strokeColor: '#064E3B',
      strokeWidth: 2.5,
      backgroundColor: 'rgba(6, 78, 59, 0.9)',
      backgroundOpacity: 90,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 7,
      animation: 'fade',
      wordEffect: 'karaoke_highlight',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  minimal_luxury: {
    short: {
      ...defaultBase,
      styleType: 'minimal_luxury',
      fontFamily: 'Almarai',
      fontSize: 44,
      primaryColor: '#FFFFFF',
      highlightColor: '#FACC15',
      strokeColor: '#000000',
      strokeWidth: 3,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 75,
      wordsPerLine: 4,
      animation: 'none',
      wordEffect: 'classic',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'minimal_luxury',
      fontFamily: 'Almarai',
      fontSize: 28,
      primaryColor: '#FFFFFF',
      highlightColor: '#FACC15',
      strokeColor: '#000000',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 8,
      animation: 'none',
      wordEffect: 'classic',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  comic_pop: {
    short: {
      ...defaultBase,
      styleType: 'comic_pop',
      fontFamily: 'Kufam',
      fontSize: 50,
      primaryColor: '#FEF08A',
      highlightColor: '#38BDF8',
      strokeColor: '#000000',
      strokeWidth: 5,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 72,
      wordsPerLine: 3,
      animation: 'pop',
      wordEffect: 'pop_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'comic_pop',
      fontFamily: 'Kufam',
      fontSize: 32,
      primaryColor: '#FEF08A',
      highlightColor: '#38BDF8',
      strokeColor: '#000000',
      strokeWidth: 3,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 6,
      animation: 'pop',
      wordEffect: 'pop_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  cinematic: {
    short: {
      ...defaultBase,
      styleType: 'cinematic',
      fontFamily: 'El Messiri',
      fontSize: 46,
      primaryColor: '#FEF08A',
      highlightColor: '#FACC15',
      strokeColor: '#000000',
      strokeWidth: 3.5,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      backgroundOpacity: 70,
      positionXPercent: 50,
      positionYPercent: 76,
      wordsPerLine: 4,
      animation: 'fade',
      wordEffect: 'classic',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'cinematic',
      fontFamily: 'El Messiri',
      fontSize: 30,
      primaryColor: '#FEF08A',
      highlightColor: '#FACC15',
      strokeColor: '#000000',
      strokeWidth: 2.5,
      backgroundColor: 'rgba(0, 0, 0, 0.75)',
      backgroundOpacity: 75,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 8,
      animation: 'fade',
      wordEffect: 'classic',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  fire_energy: {
    short: {
      ...defaultBase,
      styleType: 'fire_energy',
      fontFamily: 'Rubik',
      fontSize: 50,
      primaryColor: '#FFFFFF',
      highlightColor: '#FB923C',
      strokeColor: '#7C2D12',
      strokeWidth: 4.5,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 73,
      wordsPerLine: 4,
      animation: 'bounce',
      wordEffect: 'pop_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'fire_energy',
      fontFamily: 'Rubik',
      fontSize: 30,
      primaryColor: '#FFFFFF',
      highlightColor: '#FB923C',
      strokeColor: '#7C2D12',
      strokeWidth: 2.5,
      backgroundColor: 'transparent',
      backgroundOpacity: 0,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 7,
      animation: 'bounce',
      wordEffect: 'pop_active',
      textTransform: 'none',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
  pastel_soft: {
    short: {
      ...defaultBase,
      styleType: 'pastel_soft',
      fontFamily: 'Lemonada',
      fontSize: 44,
      primaryColor: '#FDF2F8',
      highlightColor: '#F472B6',
      strokeColor: '#831843',
      strokeWidth: 3.5,
      backgroundColor: 'rgba(131, 24, 67, 0.75)',
      backgroundOpacity: 75,
      positionXPercent: 50,
      positionYPercent: 75,
      wordsPerLine: 4,
      animation: 'pop',
      wordEffect: 'karaoke_highlight',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
    long: {
      ...defaultBase,
      styleType: 'pastel_soft',
      fontFamily: 'Lemonada',
      fontSize: 28,
      primaryColor: '#FDF2F8',
      highlightColor: '#F472B6',
      strokeColor: '#831843',
      strokeWidth: 2.5,
      backgroundColor: 'rgba(131, 24, 67, 0.8)',
      backgroundOpacity: 80,
      positionXPercent: 50,
      positionYPercent: 86,
      wordsPerLine: 7,
      animation: 'pop',
      wordEffect: 'karaoke_highlight',
      textTransform: 'box',
      hasShadow: false,
      shadowBlur: 0,
    },
  },
};
